In [2]:
import tensorflow as tf

In [29]:
a=tf.constant([2], name='constant_a')
b=tf.constant([3], name='constant_b')

In [30]:
tf.print(a.numpy()[0])

2


In [31]:
@tf.function
def add(a,b):
    c=tf.add(a,b)
    print(c)
    return c

result=add(a,b)

Tensor("Add:0", shape=(1,), dtype=int32)


In [32]:
tf.print(result[:])

[5]


In [33]:
Scalar = tf.constant(2)
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )

print ("Scalar (1 entry):\n %s \n" % Scalar)

print ("Vector (3 entries) :\n %s \n" % Vector)

print ("Matrix (3x3 entries):\n %s \n" % Matrix)

print ("Tensor (3x3x3 entries) :\n %s \n" % Tensor)

Scalar (1 entry):
 tf.Tensor(2, shape=(), dtype=int32) 

Vector (3 entries) :
 tf.Tensor([5 6 2], shape=(3,), dtype=int32) 

Matrix (3x3 entries):
 tf.Tensor(
[[1 2 3]
 [2 3 4]
 [3 4 5]], shape=(3, 3), dtype=int32) 

Tensor (3x3x3 entries) :
 tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]], shape=(3, 3, 3), dtype=int32) 



In [37]:
Tensor.shape

TensorShape([3, 3, 3])

In [50]:
#Element-wise addition, multiplication etc. 
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

@tf.function
def add():
    add_1_operation = tf.add(Matrix_one, Matrix_two)
    return add_1_operation



print ("Defined using tensorflow function :")
add_1_operation = add()
tf.print(add_1_operation[:,:])
print ("Defined using normal expressions :")
add_2_operation = Matrix_two / Matrix_one
tf.print(add_2_operation)

#For matrix-wise multiplication:
print("Defined matrix type multiplication :")
mat_mult=tf.matmul(Matrix_one, Matrix_two)
tf.print(mat_mult)

Defined using tensorflow function :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions :
[[2 1 0.66666666666666663]
 [1 0.66666666666666663 0.5]
 [0.66666666666666663 0.5 0.4]]
Defined matrix type multiplication :
[[12 12 12]
 [18 18 18]
 [24 24 24]]


In [8]:
y=tf.Variable(0)
tf.print(y)

0


In [9]:
@tf.function
def increment_by_one(y):
    y=tf.add(y,1)
    return y

for i in range(5):
    y = increment_by_one(y)
    tf.print(y)

1
2
3
4
5


In [12]:
y=tf.Variable(0)
y=tf.add(y,10)
tf.print(y)

10


In [13]:
y=tf.Variable(0)
y=tf.subtract(y,10)
tf.print(y)

-10


In [17]:
y=tf.Variable(10)
y=tf.multiply(y,10)
tf.print(y)

100


In [18]:
y=tf.Variable(100)
y=tf.divide(y,10)
tf.print(y)

10
